{% set version = "4.0.0" %}

package:
  name: munch
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/munch/munch-{{ version }}.tar.gz
  sha256: 542cb151461263216a4e37c3fd9afc425feeaf38aaa3025cd2a981fadb422235

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pbr >=3.0
    - setuptools >=61
    - pip
  run:
    - python >=3.8
    - six

test:
  imports:
    - munch
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/Infinidat/munch
  license: MIT
  license_file: LICENSE.txt
  summary: A dot-accessible dictionary (a la JavaScript objects)

extra:
  recipe-maintainers:
    - ocefpaf
